feat: wedding info api
dnd-side-project/dnd-8th-8-backend pull request #122
Opened 2023-02-27 08:22 UTC by junghoon-vans

## Related Issue

#61 

## Description

결혼 정보 API를 구현합니다.

- [X] 결혼 정보 등록
- [ ] 결혼식 날짜 조회
- [ ] 결혼식 날짜 수정
- [ ] 예산 조회
- [ ] 예산 수정

## Screenshots (if appropriate):

2023-02-27 23:57 UTC, Chaerim1001 requested changes

2023-02-27 23:57 UTC, Chaerim1001 commented on src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
> +public class Wedding extends BaseTimeEntity {
`WeddingInfo`는 어떨까요?

2023-02-28 01:57 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/wedding/Wedding.java
> +public class Wedding extends BaseTimeEntity {
결혼을 등록한다는 의미에서 Weddin이라는 네이밍을 사용하였습니다. 
이와 맞게 문서도 업데이트 해두었습니다.

2023-02-28 05:16 UTC, Chaerim1001 approved these changes
수고 많으셨습니다!!

2023-02-28 08:56 UTC, merged