refactor: reorder annotations
dnd-side-project/dnd-8th-8-backend pull request #156
Opened 2023-03-10 04:39 UTC by junghoon-vans

## Related Issue

#139 

## Description

어노테이션 순서 정의에 따라 수정합니다.

## Screenshots (if appropriate):

2023-03-10 07:59 UTC, Chaerim1001 requested changes
`transaction/dto` 에 있는 파일도 함께 수정 부탁드려요!

2023-03-10 08:00 UTC, Chaerim1001 commented
추가로 `oauth/handler` 에 있는 파일들은 이야기를 못했는데 `Component`가 먼저 오고 `Constructor`가 뒤에 오는게 어떨까요?

2023-03-10 08:58 UTC, junghoon-vans commented
> 추가로 `oauth/handler` 에 있는 파일들은 이야기를 못했는데 `Component`가 먼저 오고 `Constructor`가 뒤에 오는게 어떨까요?

좋은거 같아요. 이따가 작업해서 올려둘게요!

2023-03-10 08:58 UTC, junghoon-vans commented
> `transaction/dto` 에 있는 파일도 함께 수정 부탁드려요!

넵 알겠습니다!

2023-03-11 06:39 UTC, Chaerim1001 approved these changes
봐야하는 코드가 많았는데 수고해주셔서 감사합니다!

2023-03-11 10:06 UTC, merged