refactor: add subitem option to checklist api
dnd-side-project/dnd-8th-8-backend pull request #164
Opened 2023-03-27 08:41 UTC by Chaerim1001

## Related Issue
#163 
## Description
체크리스트 조회 시 서브 아이템 조회 유무를 `query`를 사용하여 선택할 수 있도록 수정하였습니다.
## Screenshots (if appropriate):

2023-03-27 09:14 UTC, junghoon-vans requested changes

2023-03-27 09:14 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
혹시 `findChecklistItem`이 체크리스트와 서브아이템을 함께 보여주는 서비스인가요? 그렇다면 `findChecklistWithSubitem`과 같이 좀 더 명시적으로 써주는게 더 좋은 방식인거 같습니다.

2023-03-27 09:32 UTC, Chaerim1001 commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
`withSubitem`과 `withoutSubitem`으로 구분하였습니다!

2023-03-27 09:55 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
서브아이템을 안보내는게 디폴트 액션이니까 without은 명시 안하는건 어떨까요?
`findChecklist`만 해도 그 의미가 충분히 들어가 있는거 같습니다.

2023-03-27 10:43 UTC, Chaerim1001 commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
`findChecklist`는 item과 subitem을 같이 보내고 `findChecklistWithoutSubitem`이 item만 전달되도록 하는건 어떨까요?

2023-03-27 14:26 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
음.. 보통 Rest API에서 요청을 한다고 하면 해당 리소스 하나에 대한 리스폰스가 오는게 디폴트라고 보는게 일반적이라고 생각해서요.
추가적인 서브아이템이 있는 경우가 예외적 상황이라 볼 수 있을 거 같습니다.

따라서 `findChecklist` -> 체크리스트에 대해 요청한다.
`findChecklistWithSubitem` -> 체크리스트와 그 하위 항목을 요청한다.

이렇게 구분하는게 더 좋은 방식이지 않을까 싶어서 말씀드린 겁니다!

2023-03-28 05:42 UTC, Chaerim1001 commented on src/main/java/com/dnd/weddingmap/domain/checklist/service/ChecklistService.java
> +  List<ChecklistItemDto> findChecklistItem(Long memberId);
아 이해했습니다! 수정하도록 하겠습니다 ☺️

2023-03-28 08:36 UTC, junghoon-vans approved these changes
LGTM

2023-03-28 09:23 UTC, merged