feat: checklist api
dnd-side-project/dnd-8th-8-backend pull request #58
Opened 2023-02-12 15:16 UTC by Chaerim1001

## Related Issue
#49 

## Description
체크리스트와 관련된 API를 구현합니다.

**Checklist Item**
- [x] 상세 조회
- [ ] 생성
- [ ] 수정
- [ ] 삭제

**Checklist Sub Item**
- [ ] 생성
- [ ] 수정
- [ ] 삭제

**Checklist**
- [ ] 전체 조회
## Screenshots (if appropriate):

2023-02-16 11:05 UTC, junghoon-vans requested changes

2023-02-16 11:05 UTC, junghoon-vans commented on src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
> +@ExtendWith(RestDocumentationExtension.class)
두 어노테이션 없이도 잘 동작하지 않나요?
특히 두 번쨰는 이미 AbstractRestDocsTests에 정의된 거라 중복해서 할 필요가 없을 거 같습니다.

2023-02-16 11:05 UTC, junghoon-vans commented on src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
> +  MockMvc mockMvc;
해당 변수는 이미 AbstractRestDocsTests에 정의되어 있습니다.

2023-02-16 11:05 UTC, junghoon-vans commented on src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
> +  MockMvc mockMvc;
이외 다른 컨트롤러도 확인해주세요

2023-02-16 13:39 UTC, Chaerim1001 commented on src/test/java/com/dnd/wedding/domain/checklist/checklistsubitem/controller/ChecklistSubItemControllerTest.java
> +@ExtendWith(RestDocumentationExtension.class)
수정하였습니다!

2023-02-18 17:09 UTC, junghoon-vans requested changes

2023-02-18 17:09 UTC, junghoon-vans commented on src/main/java/com/dnd/wedding/domain/checklist/checklistitem/service/ChecklistItemService.java
> +  List<ChecklistSubItem> saveChecklistSubItems(
Items는 Item과 구분하는데 혼동하기 쉬우므로 ItemList가 더 좋을 것 같습니다.

2023-02-18 17:09 UTC, junghoon-vans commented on src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/ChecklistSubItem.java
> +  public ChecklistSubItem updateState(UpdateChecklistSubItemDto checklistSubItemDto) {
Dto 네이밍이 해당 함수와 어울리지 않는 것 같습니다.
Update라는 이름이 있어 위 Dto와도 역할이 혼동되는 것 같습니다.

2023-02-18 17:47 UTC, Chaerim1001 commented on src/test/java/com/dnd/wedding/domain/checklist/checklistitem/controller/ChecklistItemControllerTest.java
> +    when(checklistItemService.findChecklistItemById(anyLong())).thenReturn(
둘의 차이가 거의 없는 것 같아 `when() `으로 사용했는데 `given/when/then` 으로 작성할 때 가독성을 더 높일 수 있겠네요. 리뷰 반영하여 수정하였습니다!

2023-02-18 17:48 UTC, Chaerim1001 commented on src/main/java/com/dnd/wedding/domain/checklist/checklistsubitem/ChecklistSubItem.java
> +  public ChecklistSubItem updateState(UpdateChecklistSubItemDto checklistSubItemDto) {
`ChecklistSubItemStateDto`로 변경하였습니다!

2023-02-19 04:00 UTC, junghoon-vans approved these changes
늦은 시간까지 수고하셨습니다!

2023-02-19 05:37 UTC, merged