feat: project initial settings
dnd-side-project/dnd-8th-8-backend pull request #6
Opened 2023-01-12 17:16 UTC by Chaerim1001

## Related Issue
#5 

## Description
- springboot 어플리케이션 초기 세팅
- mysql 세팅 (docker 사용)
    - 프로젝트 최상단 위치에 `.env` 파일 추가가 필요합니다.
    - mysql 환경변수 설정을 위해 `main/resources/` 위치에 `env.properties` 파일 추가가 필요합니다.
    - 프로젝트 루트 위치에서 `docker compose up -d` 명령을 통해 mysql 컨테이너를 동작시킨 후 어플리케이션 실행이 가능합니다.
- flyway 세팅
## Screenshots (if appropriate):

2023-01-12 17:32 UTC, junghoon-vans commented
세팅해야 되는 게 많았는데 수고해주셔서 감사합니다.
몇 가지 개선하면 좋을 거 같은 부분이 있어서 남기겠습니다.

- 브랜치명은 이슈 번호가 아니라 **이슈 제목**으로 통일하는 게 좋을 거 같습니다.
- **작업 항목에 따라 커밋**을 남겨주시면 변동사항을 쉽게 공유할 수 있습니다.
  - 예를 들면 다음과 같은 방식입니다.
    - 스프링 프로젝트 생성한 이후 커밋
      - `chore: create springboot project`
    - 스프링 디펜던시를 추가한 이후 커밋
      - `chore: add flyway dependency to gradle.build`
    - 도커 컴포즈 파일 추가
      - `chore: add docker-compose to run mysql server`

2023-01-12 17:37 UTC, junghoon-vans requested changes

2023-01-12 17:37 UTC, junghoon-vans commented on src/main/resources/application.properties
> +# ?? ??
되도록 의미없는 주석은 지워주시면 감사하겠습니다.

2023-01-12 17:38 UTC, junghoon-vans commented on docker-compose.yml
> +    image: arm64v8/mysql:8.0.28-oracle
`mysql/mysql-server:latest` 또는 `mysql/mysql-server:8.0.31`를 사용하면 될 것 같습니다.

2023-01-12 17:45 UTC, junghoon-vans commented on src/main/resources/application.properties
> +# ?? ??
추가적으로 `application.properties` 대신 `application.yml`을 사용하는 방법은 어떤지 의논해보면 좋겠습니다.

2023-01-12 18:29 UTC, Chaerim1001 commented on docker-compose.yml
> +    image: arm64v8/mysql:8.0.28-oracle
`mysql/mysql-server:8.0.31`로 수정하였습니다.

2023-01-12 18:30 UTC, Chaerim1001 commented on src/main/resources/application.properties
> +# ?? ??
한글 패치 문제로 인해 주석이 이상하게 보였네요.. 주석 수정했습니다. 추가로 `application.yml`로 파일 타입 변경하였습니다.

2023-01-13 00:56 UTC, junghoon-vans approved these changes
새벽 늦게까지 수고해주셔서 감사합니다. ☺️

2023-01-13 01:36 UTC, merged