Feature/budget api
dnd-side-project/dnd-8th-8-backend pull request #97
Opened 2023-02-21 16:06 UTC by Chaerim1001

## Related Issue
#91 
## Description
예산표 관련 API를 구현합니다.

**Transaction** `/api/v1/budget/transaction/{transaction-id}`

- [x] 상세 조회
- [x] 리스트 조회
- [x] 생성
- [x] 수정
- [x] 삭제

## Screenshots (if appropriate):

2023-02-22 14:33 UTC, junghoon-vans requested changes

2023-02-22 14:33 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
> +  private TransactionCategory transactionCategory;
거래구분을 나타내는 필드명이 카테고리인건 조금 어색한 느낌이 있는 것 같습니다.
`PaymentType`이나 `PaymentOption` 등이 더 적절한 것 같네요

2023-02-22 14:33 UTC, junghoon-vans commented on src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
> +  private TransactionCategory transactionCategory;
추가적으로 `PaymentMethod`도 가능할 것 같아요.

2023-02-22 15:13 UTC, Chaerim1001 commented on src/main/java/com/dnd/weddingmap/domain/transaction/Transaction.java
> +  private TransactionCategory transactionCategory;
`PaymentType`으로 변경하였습니다!

2023-02-23 07:56 UTC, junghoon-vans approved these changes
수고 많으셨습니다 👍

2023-02-23 07:57 UTC, merged